import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react'
import { imageDimensions } from '@/data/projects'
import { LightboxImage } from '@/components/Lightbox'

/**
 * GalleryStripMobile — justified-row gallery for the mobile work archive and
 * case study pages. Image dimensions come from the build-time manifest in
 * src/data/projects.ts (regenerated by `npm run measure-images`) so there's
 * no runtime probing and no layout shift.
 *
 *   target row height ≈ 32vh  (clamped 22vh–38vh for non-orphan rows)
 *   orphan (last incomplete) row sits at target height, left-aligned, no upscale
 *
 * Each item is a LightboxImage so taps open the fullscreen viewer.
 */
interface Props {
  images: string[]
  group: string
  /** Override the gap in px. Defaults to 8 (gap-2). */
  gap?: number
}

interface PackedItem {
  src: string
  w: number  // rendered width in px
  h: number  // rendered height in px
}

interface PackedRow {
  items: PackedItem[]
  h: number
  orphan: boolean
}

const DEFAULT_GAP = 8

function packJustified(
  items: { src: string; w: number; h: number }[],
  containerWidth: number,
  targetH: number,
  minH: number,
  maxH: number,
  gap: number,
): PackedRow[] {
  const rows: PackedRow[] = []
  let buf: { src: string; ar: number }[] = []
  let arSum = 0

  const finalize = (h: number, orphan: boolean) => {
    // Cap at maxH so a single landscape image doesn't blow the row up.
    // We do NOT clamp UP to minH here — that would force widths to exceed
    // containerWidth. Rows below minH only happen as orphans or when a
    // single very-wide image's natural h falls below minH.
    const finalH = Math.min(maxH, h)
    rows.push({
      items: buf.map(({ src, ar }) => ({ src, w: ar * finalH, h: finalH })),
      h: finalH,
      orphan,
    })
    buf = []
    arSum = 0
  }

  for (const it of items) {
    const ar = it.w / it.h
    const newArSum = arSum + ar
    const newBufLen = buf.length + 1
    const newGaps = (newBufLen - 1) * gap
    const newH = (containerWidth - newGaps) / newArSum

    if (newH < minH && buf.length > 0) {
      // Including this image would shrink the row below minH. Finalize the
      // current buf without it (taller, fewer-image row), then seed the
      // next row with this image.
      const curGaps = (buf.length - 1) * gap
      const curH = (containerWidth - curGaps) / arSum
      finalize(curH, false)
      buf.push({ src: it.src, ar })
      arSum = ar
      continue
    }

    buf.push({ src: it.src, ar })
    arSum = newArSum
    if (newH <= targetH) {
      finalize(newH, false)
    }
  }

  if (buf.length > 0) {
    // Orphan row sits at targetH (no upscale). Left-aligned; row may be
    // narrower than the container.
    finalize(targetH, true)
  }

  return rows
}

export function GalleryStripMobile({ images, group, gap = DEFAULT_GAP }: Props) {
  const ref = useRef<HTMLDivElement>(null)
  // Seed containerWidth from window.innerWidth so the row packer can compute
  // rows on the very first render — otherwise the component renders an
  // empty div until useLayoutEffect fires, which pushes every section below
  // it (notably the next-project tap target) down by thousands of pixels
  // mid-frame. That's a CLS catastrophe. ResizeObserver refines the value
  // post-mount if needed. -40 is the parent's px-5 horizontal padding.
  const [containerWidth, setContainerWidth] = useState(() =>
    typeof window === 'undefined' ? 350 : Math.max(0, window.innerWidth - 40),
  )
  const [vh, setVh] = useState(() => (typeof window === 'undefined' ? 844 : window.innerHeight))

  useLayoutEffect(() => {
    if (!ref.current) return
    const measure = () => {
      if (ref.current) setContainerWidth(ref.current.offsetWidth)
    }
    measure()
    const ro = new ResizeObserver(measure)
    ro.observe(ref.current)
    return () => ro.disconnect()
  }, [])

  useEffect(() => {
    const onResize = () => setVh(window.innerHeight)
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [])

  const rows = useMemo(() => {
    if (containerWidth <= 0) return []
    const targetH = vh * 0.32
    const minH = vh * 0.22
    const maxH = vh * 0.38
    const items = images.map((src) => {
      const dim = imageDimensions[src]
      // Fallback to a neutral 4:3 if a src isn't in the manifest. The script
      // covers everything in public/images/work, so this should never fire
      // for case-study plates.
      return { src, w: dim?.w ?? 4, h: dim?.h ?? 3 }
    })
    return packJustified(items, containerWidth, targetH, minH, maxH, gap)
  }, [images, containerWidth, vh, gap])

  return (
    <div ref={ref} className="w-full">
      {/* Reserve the page height up front using the known intrinsic dimensions
          so first paint doesn't stretch the page when rows resolve. */}
      <div className="flex flex-col" style={{ gap: `${gap}px` }}>
        {rows.map((row, i) => (
          <div
            key={i}
            className="flex justify-start"
            style={{ gap: `${gap}px` }}
          >
            {row.items.map((it, j) => (
              <LightboxImage
                key={`${it.src}-${j}`}
                src={it.src}
                group={group}
                alt=""
                loading={i < 2 ? 'eager' : 'lazy'}
                decoding="async"
                className="block object-cover"
                style={{
                  width: `${it.w}px`,
                  height: `${it.h}px`,
                  flex: '0 0 auto',
                }}
              />
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}
